# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('theme_id', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=99)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.News')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
